name: Build & Deploy CSS

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Versioning
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.new_tag }}
      version: ${{ steps.version.outputs.new_version }}
      changelog: ${{ steps.version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          name: ${{ steps.version.outputs.new_tag }}
          body: ${{ steps.version.outputs.changelog }}

  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - uses: actions/checkout@v3

      - name: Fetch & Pull
        run: |
          git fetch
          git pull

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - run: yarn --immutable

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ needs.version.outputs.version }}

      - run: yarn build

      - uses: svenstaro/upload-release-action@v2
        with:
          file: 'dist/theme.css'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.version.outputs.tag }}
          asset_name: 'vencord.theme-${{ needs.version.outputs.version }}.css'
          body: ${{ needs.version.outputs.changelog }}

      - name: Copy file to versions folder and update latest
        run: |
          cp dist/theme.css versions/vencord.theme-${{ needs.version.outputs.version }}.css
          rm versions/latest.css
          cp dist/theme.css versions/latest.css

      - name: Commit updated package.json & credits.sass
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "Update versions (${{ needs.version.outputs.version }})"
          commit_options: "--no-verify"
          commit_user_name: "GitHub Actions"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"
          file_pattern: "package.json versions/*.css theme.css"
          push_options: '--force'
          skip_fetch: false