name: Build & Deploy CSS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - run: yarn install

      - run: yarn build

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'theme.css'
          tag: ${{ github.ref }}
          asset_name: 'vencord.theme.css'
          overwrite: true
          body: ${{ github.event.head_commit.message }}